[rails 4.1.10 upgrade, models] Not quite sure why we need to reload here, but it's innocuous enough and, fixes 10 failing specs.  :)
  10) ImportExecutor#run where the workspace has been deleted creates a WorkspaceImportFailed
     Failure/Error: destination.destroy
     NoMethodError:
       undefined method `target_date' for nil:NilClass
     # ./app/models/milestone.rb:24:in `update_workspace_target_date'
     # ./app/models/milestone.rb:20:in `project_hooks'
     # ./app/mixins/soft_delete.rb:10:in `destroy'
     # ./spec/services/import_executor_spec.rb:161:in `(root)'