[rails 4 upgrade, API controllers] Fixing broken test:
  7) Alpine::CredentialsController#show when alpine is enabled for local requests works for ::ffff:127.0.0.1
     Failure/Error: get :show, :data_source_id => data_source.id
     NoMethodError:
       undefined method `+' for #<Regexp:0x78236c8b>

ActionDispatch::Request::LOCALHOST is no longer an array ...